### ISSUE TITLE
Fails to install on Xcode 13

### ISSUE THREAD

**Issue by samuelowino** [wakatime/xcode-wakatime#63] opened 2022-05-19 19:40 UTC

**Comment by gandarez** [comment] 2022-05-20 15:19
@samuelowino without detailed ifo we can guess what happened. Enable `debug = true` in your `~/.wakatime.cfg` and check for any errors. Feel free to attach some of them here.

**Comment by alanhamlett** [comment] 2022-05-20 15:46
Most likely a duplicate of #61. @samuelowino if you're getting a different error than the one in #61 please paste it here and we can re-open this issue.

**Closed by alanhamlett** 2022-05-20 15:46 UTC

**Comment by samuelowino** [comment] 2022-05-22 00:27
Hey @gandarez @alanhamlett , I noticed that there are already issues open with the exact same error log. Unfortunately none with Xcode 13. Let me add some error logs to my issues description

**Comment by samuelowino** [comment] 2022-05-22 17:43
@gandarez @alanhamlett  check issue description, seems like Alcatraz fails to install.

**Comment by samuelowino** [comment] 2022-05-22 17:45
@alanhamlett you are too quick to close issues, please look at the description above

**Comment by samuelowino** [comment] 2022-05-22 20:27
Reinstalling wakatime-cli solved the issue for me.

bash <(curl -s https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/WakaTime/install_dependencies.sh)

**Comment by alanhamlett** [comment] 2022-05-23 04:06
Looks like it failed when installing Alcatraz. Maybe we don't need Alcatraz anymore, since it's no longer supported.

**Comment by samuelowino** [comment] 2022-05-23 09:22
It's definitely Alcatraz.

I also wanted to use method 2: creating a copy of Xcode so that I can preserve the original Xcode app signature, because I still want to use Xcode  to upload builds to App Store connect. I had a previous installation that refused Apple ID registration due to the plugin corrupting Xcode signature.

Some innovation around this would be awesome.

**Comment by samuelowino** [comment] 2022-05-23 09:23
Thanks, the plugin is awesome!

**Comment by alanhamlett** [comment] 2022-05-23 14:51
I removed Alcatraz from the install script and it seems to work fine without it. Should be fixed 👍
